version: '3.9'
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    hostname: tailscale-digitalocean
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/raghav/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--login-server=https://change_me_here.silver1618.fun/ --advertise-exit-node --advertise-routes=192.168.1.0/24 --accept-dns=true
      - TS_NO_LOGS_NO_SUPPORT=true
      - TS_AUTHKEY=change_me_here  
    restart: unless-stopped