---
- name: Include Encrypted Variables
  include_vars:
    file: secrets.yaml
    
- name: install docker env
  ansible.builtin.apt:
    name: 
      - docker.io
      - docker-compose
    state: latest
    update_cache: yes
    install_recommends: no

- name: Add docker to user grp
  ansible.builtin.shell: usermod -aG docker "{{ myuser }}"

- name: copy tailscale compose file for backup
  copy:
    src: ./docker-compose.yaml
    dest: /home/{{ myuser }}/docker-compose.yaml

- name: Join my tailsclae network
  become: true
  become_user: "{{ myuser }}"
  community.docker.docker_compose:
    project_name: tailscale
    definition:
      version: '3.9'
      services:
        tailscale:
          container_name: tailscale
          image: tailscale/tailscale:stable
          hostname: tailscale-digitalocean
          security_opt:
            - no-new-privileges:true
          volumes:
            - /home/{{ myuser }}/tailscale:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
          network_mode: "host"
          cap_add:
            - NET_ADMIN
            - NET_RAW
          environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_EXTRA_ARGS=--login-server={{ my_tailscale_web }} --advertise-exit-node --advertise-routes=192.168.1.0/24 --accept-dns=true
            - TS_NO_LOGS_NO_SUPPORT=true
            - TS_AUTHKEY={{ my_token }}  
          restart: unless-stopped
