---
- hosts: on_demand_droplets
  become: yes
  gather_facts: false
  tasks:
    - name: install env
      ansible.builtin.apt:
        name: 
          - tmux
          - zsh
          - exa
          - unzip
          - fontconfig
        state: latest
        update_cache: yes
        install_recommends: no

    - name: Create fonts direcory
      become: yes
      become_user: "{{ myuser }}"
      ansible.builtin.command: mkdir /home/{{ myuser }}/.fonts/
      ignore_errors: true

    - name: Download Firacode fonts
      become: yes
      become_user: "{{ myuser }}"
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip
        dest: /home/{{ myuser }}/.fonts/
        remote_src: yes
        validate_certs: false

    - name: Clone my zsh files
      become: yes
      become_user: "{{ myuser }}"
      shell: git clone https://github.com/silversurfer98/zsh_setup.git /home/{{ myuser }}/zsh_setup

    - name: Install starship
      become: yes
      become_user: "{{ myuser }}"
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
    - name: Do not count this as a failure
      ansible.builtin.command: fc-cache -fv
      ignore_errors: true

    - name: Copy configs
      become: yes
      become_user: "{{ myuser }}"
      shell: |
        cp -Rf /home/{{ myuser }}/zsh_setup/.zsh /home/{{ myuser }}/
        cp -Rf /home/{{ myuser }}/zsh_setup/.config /home/{{ myuser }}/
        cp -f /home/{{ myuser }}/zsh_setup/.zshrc /home/{{ myuser }}/

    - name: Initialize ZSH
      ansible.builtin.shell:
        cmd: source /home/{{ myuser }}/.zshrc
      vars:
        ansible_shell_executable: /bin/zsh
